<%@ Page Title=""
  Language="C#"
  MasterPageFile="~/Admin Panel/Admin.master"
  AutoEventWireup="true"
  CodeFile="orders.aspx.cs"
  Inherits="Admin_Panel_orders" %>

<asp:Content ID="Content1"
  ContentPlaceHolderID="AdminPanelhead"
  runat="Server">
</asp:Content>
<asp:Content ID="Content2"
  ContentPlaceHolderID="AdminPanelMaster"
  runat="Server">
  <%--LISTING 11.20 ShowCommandField.aspx--%>
  <asp:UpdatePanel
    ID="UpdatePanel1"
    runat="server">
    <ContentTemplate> <asp:GridView ID="GridView1"
    runat="server"
    AllowPaging="True"
    AllowSorting="True"
    AutoGenerateColumns="False"
    CellPadding="4"
    DataSourceID="SqlDataSource1"
    DataKeyNames="order_id"
    EnableModelValidation="True"
    ForeColor="#333333"
    GridLines="None"
    AutoGenerateEditButton="True"
    AutoGenerateDeleteButton="True"
    OnRowUpdated="GridView1_RowUpdated">
    <AlternatingRowStyle
      BackColor="White" />
    <Columns>
      <asp:BoundField
        DataField="order_id"
        HeaderText="order_id"
        InsertVisible="False"
        ReadOnly="True"
        SortExpression="order_id" />
      <asp:BoundField
        DataField="products_title"
        HeaderText="products_title"
        SortExpression="products_title"
        ReadOnly="True" />
      <asp:BoundField
        DataField="O_price"
        HeaderText="O_price"
        SortExpression="O_price"
        ReadOnly="True" />
      <asp:BoundField
        DataField="order_date"
        HeaderText="order_date"
        SortExpression="order_date"
        ReadOnly="True" />
      <asp:BoundField
        DataField="o_status"
        HeaderText="o_status"
        SortExpression="o_status" />
      <asp:BoundField
        DataField="quantities"
        HeaderText="quantities"
        SortExpression="quantities"
        ShowHeader="True"
        ReadOnly="True" />
    </Columns>
    <EditRowStyle BackColor="#2461BF" />
    <FooterStyle BackColor="#507CD1"
      Font-Bold="True"
      ForeColor="White" />
    <HeaderStyle BackColor="#999999"
      Font-Bold="True"
      ForeColor="White" />
    <PagerStyle BackColor="#999999"
      ForeColor="White"
      HorizontalAlign="Center"
      Font-Size="X-Large" />
    <RowStyle BackColor="#EFF3FB" />
    <SelectedRowStyle
      BackColor="#D1DDF1"
      Font-Bold="True"
      ForeColor="#333333" />
  </asp:GridView>
    </ContentTemplate>
  </asp:UpdatePanel>
 
  <asp:SqlDataSource
    ID="SqlDataSource1"
    runat="server"
    ConnectionString="<%$ ConnectionStrings:HomeConnectionString %>"
    SelectCommand="SELECT [order_id], [products_title], [O_price], [order_date], [o_status], [quantities] FROM [Order_details] WHERE ([o_status] = @o_status) ORDER BY [order_date] DESC"
    UpdateCommand="UPDATE Order_details set o_status=@o_status WHERE order_id=@order_id"
    DeleteCommand="DELETE FROM Order_details WHERE order_id=@order_id"
    
    OnUpdated="SqlDataSource1_Updated" 
    onupdating="SqlDataSource1_Updating">
    <SelectParameters>
      <asp:Parameter DefaultValue="processing"
        Name="o_status"
        Type="String" />
    </SelectParameters>
  </asp:SqlDataSource>
</asp:Content>
