<%@ Page Title="" Language="C#" MasterPageFile="~/Admin Panel/Admin.master" AutoEventWireup="true"
    CodeFile="orders.aspx.cs" Inherits="Admin_Panel_orders" %>

<asp:Content ID="Content1" ContentPlaceHolderID="AdminPanelhead" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AdminPanelMaster" runat="Server">
    <%--LISTING 11.20 ShowCommandField.aspx--%>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True"
        AutoGenerateColumns="False" CellPadding="4" DataKeyNames="order_no" DataSourceID="SqlDataSource1"
        EnableModelValidation="True" ForeColor="#333333" GridLines="None" AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:BoundField DataField="order_no" HeaderText="order_no" InsertVisible="False"
                ReadOnly="True" SortExpression="order_no" />
            <asp:BoundField DataField="products_title" HeaderText="products_title" SortExpression="products_title"
                ReadOnly="True" />
            <asp:BoundField DataField="total_amount" HeaderText="total_amount" SortExpression="total_amount"
                ReadOnly="True" />
            <asp:BoundField DataField="quantities" HeaderText="quantities" SortExpression="quantities"
                ReadOnly="True" />
            <asp:BoundField DataField="o_status" HeaderText="o_status" SortExpression="o_status" />
        </Columns>
        <EditRowStyle BackColor="#2461BF" />
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:HomeConnectionString %>"
        SelectCommand="SELECT [order_no], [products_title], [total_amount], [quantities], [o_status] FROM [Order_details] WHERE ([o_status] = @o_status)"
        DeleteCommand="DELETE FROM [Order_details] WHERE order_no = @order_no" UpdateCommand="UPDATE Order_details SET o_status = @o_status">
        <SelectParameters>
            <asp:Parameter DefaultValue="pending" Name="o_status" Type="String" />
        </SelectParameters>
    </asp:SqlDataSource>
</asp:Content>
